import = ["~/.config/alacritty/themes/themes/tokyo-night.toml"]

[window]
option_as_alt = "Both"
padding = { x = 2, y = 2 }
class = { general = "Alacritty", instance = "Alacritty" }
opacity = 0.85
blur = true
decorations = "None"

[font]
size = 12.0

[font.bold]
family = "MesloLGL Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MesloLGL Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MesloLGL Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGL Nerd Font"
style = "Regular"
