import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]


[window]
option_as_alt = "Both"
padding = { x = 2, y = 2 }
class = { general = "Alacritty", instance = "Alacritty" }
opacity = 0.70
blur = true
decorations = "None"

[font]
size = 12.0

[font.bold]
family = "MesloLGL Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MesloLGL Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MesloLGL Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGL Nerd Font"
style = "Regular"

[keyboard]
bindings = [
  # close
  { key = "W", mods = "Command", mode = "~Alt", action = "ReceiveChar" },
  { key = "Q", mods = "Command", mode = "~Alt", action = "ReceiveChar" },
  # scrollback
  { key = "PageUp", mods = "Shift", mode = "~Alt", action = "ReceiveChar" },
  { key = "PageDown", mods = "Shift", mode = "~Alt", action = "ReceiveChar" },
  { key = "Home", mods = "Shift", mode = "~Alt", action = "ReceiveChar" },
  { key = "End", mods = "Shift", mode = "~Alt", action = "ReceiveChar" },
  { key = "K", mods = "Command", mode = "~Vi|~Search", action = "ReceiveChar" },
  # searching
  { key = "F", mods = "Control|Shift", mode = "~Search", action = "ReceiveChar" },
  { key = "F", mods = "Command", mode = "~Search", action = "ReceiveChar" },
  { key = "B", mods = "Control|Shift", mode = "~Search", action = "ReceiveChar" },
  { key = "B", mods = "Command", mode = "~Search", action = "ReceiveChar" },
  # copy/paste
  # { key = "Paste", action = "ReceiveChar" },
  { key = "Copy", action = "ReceiveChar" },
  # { key = "V", mods = "Control|Shift", mode = "~Vi", action = "ReceiveChar" },
  # { key = "V", mods = "Command", action = "ReceiveChar" },
  { key = "C", mods = "Control|Shift", action = "ReceiveChar" },
  { key = "C", mods = "Command", action = "ReceiveChar" },
  { key = "C", mods = "Control|Shift", mode = "Vi|~Search", action = "ReceiveChar" },
  { key = "C", mods = "Command", mode = "Vi|~Search", action = "ReceiveChar" },
  # { key = "Insert", mods = "Shift", action = "ReceiveChar" },
]

[mouse]
hide_when_typing = true
bindings = [{ mouse = "Right", action = "ReceiveChar" }]
