# Configuration
home: ~/.config/nap/naps/
default_language: bash
theme: nord

# Colors
background: "0"
foreground: "7"
primary_color: "#e0af68"
primary_color_subdued: "#4364AA"
green: "#9ece6a"
bright_green: "#87CC3D"
bright_red: "#ff007c"
red: "#f7768e"
black: "#1d202f"
gray: "#394b70"
white: "#FFFFFF"

